apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery
  template:
    metadata:
      labels:
        app: delivery
    spec:
      containers:
        - name: delivery
          image: shubhamjain2908/delivery
          env:
            - name: MONGO_URI
              value: "mongodb://delivery-mongo-srv:27017/delivery"
---
apiVersion: v1
kind: Service
metadata:
  name: delivery-srv
spec:
  selector:
    app: delivery
  ports:
    - name: delivery
      protocol: TCP
      port: 3000
      targetPort: 3000
